[workspace]
authors = ["Chase Katz <chase1602@icloud.com>"]
channels = ["conda-forge"]
name = "ML-Microscopy-Hackathon"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
ipykernel = ">=7.1.0,<8"
pytorch = ">=2.9.1,<3"
opencv = ">=4.12.0,<5"
imageio = ">=2.37.0,<3"
matplotlib = ">=3.10.8,<4"
pip = ">=25.3,<26"
scikit-learn = ">=1.8.0,<2"
numpy = "<2"
scipy = ">=1.16.3,<2"
scikit-image = ">=0.25.2,<0.26"
pandas = ">=2.3.3,<3"
